### ISSUE TITLE
Many to Many relationships

### ISSUE THREAD

**Issue by devotionsolutions** [codecoding/SQLite4Unity3d#110]
What's the proper way to deal with many to many relationships between tables using this library?
Let's say we have three tables:

- Categories
- SubCategories
- Categories_SubCategories (including many to many relationships within the previous tables, referencing their PKs)

Like in this [diagram](https://docs.google.com/drawings/d/1BSpHYYXP5UQ_wVM7p0XVBueMxXfuuRlQsy8mK86uXJg/edit?usp=sharing)

Any idea?

**Comment by afandiyusuf** [comment]
You always can use manual queries with this library.

`Select * from categories right join categories_subcategoris on categories.id = categories_subcategories.categories_id left join sub_categories on categories_subcategories.subcategories_id = subcategories.id`

**Comment by devotionsolutions** [comment]
> You always can use manual queries with this library.
> 
> `Select * from categories right join categories_subcategoris on categories.id = categories_subcategories.categories_id left join sub_categories on categories_subcategories.subcategories_id = subcategories.id`

Great idea, but unfortunately "RIGHT and FULL OUTER JOINs are not currently supported" for sqlite

**Comment by afandiyusuf** [comment]
You could emulate RIGHT JOIN with LEFT JOIN by swapping the position table when selecting it.
```
Select * from categories_subcategoris left join categories on categories.id = categories_subcategories.categories_id left join sub_categories on categories_subcategories.subcategories_id = subcategories.id
```

Hope it help.

**Comment by devotionsolutions** [comment]
> You could emulate RIGHT JOIN with LEFT JOIN by swapping the position table when selecting it.
> 
> ```
> Select * from categories_subcategoris left join categories on categories.id = categories_subcategories.categories_id left join sub_categories on categories_subcategories.subcategories_id = subcategories.id
> ```
> 
> Hope it help.

Thanks! it worked!
