### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by IrfanKureshi8792** [codecoding/SQLite4Unity3d#112]
how to implement select * from <tableName> where EmployeeName="ABC" AND Designation="HR" ; in Sqlite4unity

**Comment by georgetye** [comment]
I'm wondering the same thing.

"You’re done! Now you can get access to your database using sqlite-net. ;P"

Except there's no explanation on how to do that? Maybe I'm just too much of a noob.

**Comment by robertohuertasm** [comment]
HI @IrfanKureshi8792 and @georgetye, please take a look at [sqlite-net wiki ](https://github.com/praeclarum/sqlite-net/wiki)for more information on how to use it.

You can use pure sql: 

```csharp
string query = $"SELECT * FROM records";
var results = conn.Query<Record>(query);
```
or linq:
```csharp
var results = conn.Table<Record>().Where(t => t.Age > 40).OrderByDescending(t => t.Age).ToList();
```

See the [Synchronouse API docs.](https://github.com/praeclarum/sqlite-net/wiki/Synchronous-API)

**Comment by georgetye** [comment]
Ah ok perfect, thanks so much!
