### ISSUE TITLE
Source of the used sqlite3-libraries

### ISSUE THREAD

**Issue by AlexSchuetz** [codecoding/SQLite4Unity3d#118]
Hi,

and first of all: Thank you for your work!

I use SQLiteNET-PCL and everything works fine except Oculus Quest 2 (android).
Thus I made a second library using your project. This worked at first.

Since this project is outdated, the API is not compatible with SQLiteNET any more. And that is the reason why I cannot use the obove approach any more and I try to get it working using SQLiteNET again.

Now I am wondering where you got the dll and so files in the zip package from?

Any hint is apprechiated.

**Comment by robertohuertasm** [comment]
Hi @AlexSchuetz, it's been a lot of time since I got those ones and can't remember 😞. I think I got them from [here](https://sqlite.org/) but I'm not sure enough. Sorry for not being of more help.

**Comment by AlexSchuetz** [comment]
Thank you nevertheless.
Meanwhile I looked for the sources myself and came to the very same conclusion. 😄

**Comment by AlexSchuetz** [comment]
Right now I am migrating back to SQLiteNET-PCL. Would you mind if I create a PR for your readme with the information how to achieve this?
I think many unity-developers will land here 😄

**Comment by robertohuertasm** [comment]
Sure, go ahead. I'll be happy to merge it!
