### ISSUE TITLE
SQLiteException

### ISSUE THREAD

**Issue by tetreum** [codecoding/SQLite4Unity3d#26]
SQLiteException: near ")": syntax error
SQLite4Unity3d.SQLite3.Prepare2 (IntPtr db, System.String query)
SQLite4Unity3d.PreparedSqlLiteInsertCommand.Prepare ()
SQLite4Unity3d.PreparedSqlLiteInsertCommand.ExecuteNonQuery (System.Object[] source)
SQLite4Unity3d.SQLiteConnection.Insert (System.Object obj, System.String extra, System.Type objType)
My table has a simple string ("33-66", "44-88" because SQLite net doesn't support multiple primary columns..).

**Comment by codecoding** [comment]
Could you provide an example scenario so I could reproduce it?

**Comment by tetreum** [comment]
I've sent you an email.

**Comment by codecoding** [comment]
To what email address? code@codecoding.com?

**Comment by tetreum** [comment]
Yes, i sent it to code@codecoding.com

**Comment by ourgames** [comment]
> SQLiteException: near ")": syntax error
> SQLite4Unity3d.SQLite3.Prepare2 (IntPtr db, System.String query)
> SQLite4Unity3d.PreparedSqlLiteInsertCommand.Prepare ()
> SQLite4Unity3d.PreparedSqlLiteInsertCommand.ExecuteNonQuery (System.Object[] source)
> SQLite4Unity3d.SQLiteConnection.Insert (System.Object obj, System.String extra, System.Type objType)
> My table has a simple string ("33-66", "44-88" because SQLite net doesn't support multiple primary columns..).

I have encountered the same problem, how do you solve it?

**Comment by ourgames** [comment]
> Could you provide an example scenario so I could reproduce it?

how do you solve it?

**Comment by hlongvu** [comment]
I have encountered this problem today, have no clue how to fix this because the library run fine before? Could you give us more details?
