### ISSUE TITLE
DllNotFoundException: sqlite3 on Android 6.0 (but on 5.x works ok)

### ISSUE THREAD

**Issue by andreimavenhut** [codecoding/SQLite4Unity3d#27]
Apparently on Nexus 5 Android 6.0 it gives an error of DllNotFoundException: sqlite3, but on other androids it works ok. Any known fixes for this ?

**Comment by codecoding** [comment]
Nope. I didn't have the chance to test it on Android 6.0. You mean the same apk works ok in different Android versions?

**Comment by andreimavenhut** [comment]
Yup. Same apk, on 6.0 doesn't work, on 4.x or 5.x works ok. The exact error is this:

**Comment by codecoding** [comment]
Ok. I'll have a look at it when I have time and let you know what I find.

**Comment by codecoding** [comment]
I've tested with the Android emulator running Android 6 and seems to be working.

![capture](https://cloud.githubusercontent.com/assets/696981/10562175/2bb9b4c0-754e-11e5-8bf2-8f9e01800387.PNG)

Could you test the example for Android? If you provide me your email I can send you the test.apk

**Comment by codecoding** [comment]
@andreimavenhut I've finally replicated the issue using ARM architecture. I'll let you know what I find.

**Comment by codecoding** [comment]
@andreimavenhut I solved the issue. Download the latest plugin folder and it should be working now.
I've tested both with ARM and x86 architecture and seem to be working ok.

Let me know if it's not working for you.

Best regards,
Roberto.

**Comment by andreimavenhut** [comment]
I just tested on a real device. It's fixed. Thanks :+1:

**Comment by codecoding** [comment]
Cool! :+1:
