### ISSUE TITLE
"insert into" not work in Android

### ISSUE THREAD

**Issue by cabanel** [codecoding/SQLite4Unity3d#29]
var q = ds.con.Execute("insert into STATISTIC (data, domande) values ('ZZZ', 3)");

this command work fine on pc not work on android

**Comment by cabanel** [comment]
I found the solution!

WHY WAS NOT UPDATED DATABASE WAS DUE
THE LACK OF APPROVAL IN WRITING

IN SETTING ANDROID IF YOU HAVE LOCATION INSTALL '' PREFER Esternal "
You MUST SET WRITE ACCESS ON "Esternal (SD CARD)"

sorry for my english

![errore](https://cloud.githubusercontent.com/assets/4569650/11144832/1692379a-8a00-11e5-84fa-1b80b7890846.png)

**Comment by robertohuertasm** [comment]
Cool you found the solution to the issue!! Thank you very much for the information! ;D

**Comment by spiffai** [comment]
I'm actually having this very same issue. I cannot create, drop, or insert into my database. I've tried every option combination for Install Location & Write Access. Same reaction. I'm using Unity 2017.1.f1. Still looking into it but if anyone knows how to fix this, please let me know.
