### ISSUE TITLE
Plugins colliding with each other when trying to build Android apk

### ISSUE THREAD

**Issue by ttpro1995** [codecoding/SQLite4Unity3d#32]
Found plugins with same names and architectures, Assets/Plugins/x64/sqlite3.dll () and Assets/Plugins/x86/sqlite3.dll (). Assign different architectures or delete the duplicate.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.HostView:OnGUI()

**Comment by sandolkakos** [comment]
You need to configure the platform settings to each dll:
1. Select Assets/Plugins/x64/sqlite3.dll
2. Go to Inspector and select the Plataforms you want to use this DLL
3. Go to CPU and select x64

4. Select Assets/Plugins/x86/sqlite3.dll
5. Go to Inspector and select the Plataforms you want to use this DLL
6. Go to CPU and select x86
