### ISSUE TITLE
How do I create a foreign key?

### ISSUE THREAD

**Issue by MEyes** [codecoding/SQLite4Unity3d#35]
Hi,
I can't find ForeignKeyAttribute,How do I create a foreign key?

**Comment by robertohuertasm** [comment]
Sorry, but SQLite-net doesn't provide this functionality.
It seems that there's a library supporting some extensions that include Foreign Key support:
https://forums.xamarin.com/discussion/2973/foreign-keys-in-sqlite-net 

There's an issue asking for the implementation of such library in this project but I don't think is going to be implemented in the near future.

Best regards.
