### ISSUE TITLE
is SQLite.cs necessary ? Is there any critical error if I am not using SQLite.cs

### ISSUE THREAD

**Issue by ttpro1995** [codecoding/SQLite4Unity3d#38]
I just find out that I forgot to copy SQLite.cs into my project.
However, my game still running fine. (except issues #37 , which the game still using old database when user install update from Google Play) 
I just want to know the role of SQLite.cs and how to use it.
I suggest you to include it in the README.md  

Thank you.

**Comment by robertohuertasm** [comment]
Hi @ttpro1995,
how are you using the library? Are you taking advantatge of the linq part? https://github.com/praeclarum/sqlite-net 
Because SQLite.cs will let you use Linq to SQLite as some sort of light ORM.
