### ISSUE TITLE
How did you compile libsqlite3.so?

### ISSUE THREAD

**Issue by timmy2702** [codecoding/SQLite4Unity3d#4]
Hi Roberto,

Your plugin works really great. I'm just wondering how you compiled libsqlite3.so from sqlite3.dll? Just for my future knowledge.

Thanks,
Tim

**Comment by codecoding** [comment]
Hi Tim,

I'm sorry to disappoint you but I didn't. I already got it compiled by someone else. Please see this: https://github.com/codecoding/SQLite4Unity3d/issues/1 and if you want more details you can contact ORuban. He was the one compiling the x86 version. 

The source code is taken from this page: http://www.sqlite.org/download.html so the idea is you use a c compiler to create the .so. If you have a Linux distro it would be easier for you to create the .so. 

Find here some instructions about how to achieve it:
http://stackoverflow.com/questions/14884126/build-so-file-from-c-file-using-gcc-command-line

I've just tried and it seem pretty straightforward.

Best regards,
Roberto
