### ISSUE TITLE
Game Compiled on Windows don't work but on editor do!

### ISSUE THREAD

**Issue by gilbertobitt** [codecoding/SQLite4Unity3d#42]
i have a problem i want to work on both android and Windows but on Windows the sqlite don't work! how i make it work? the interesting is that on Windows it work! and i wonder why! someone please help!

**Comment by robertohuertasm** [comment]
Have you followed the video tutorials?

**Comment by gilbertobitt** [comment]
but the vídeo tutorial that exist on readme isn't just about the Windows phone and UWP?

**Comment by robertohuertasm** [comment]
You have a tutorial for each platform. All you have to do is configure the settings accordingly whenever you want to deploy to a specific platform.

**Comment by gilbertobitt** [comment]
@robertohuertasm i will try now and answer with the result!

**Comment by gilbertobitt** [comment]
@robertohuertasm here is configuration.. whem i compile the game.. he don't read at all the sqlitedb and i don't know why! it's like neve was a sqlite db there. what u recomend to me to find a solution?

![2016-05-18_20-24-36](https://cloud.githubusercontent.com/assets/1363635/15378103/de3c3c54-1d36-11e6-961d-1605eccdcebf.gif)

**Comment by robertohuertasm** [comment]
@gilbertobitt I thought you were talking about Windows Store apps... I don't have now access to my windows machine. As soon as I can get to it I will let you know. But if it runs in the editor it should also run in your pc.

**Comment by gilbertobitt** [comment]
@robertohuertasm  that's is the problem.. is that is running corretly on editor but when compiled to windows x86 or windows x86_x64 both don't run! it's like never was a code to acess sqlitedb!

**Comment by Borhenec** [comment]
hi,
I have the same problem when I compile I have this error : SqliteExeption : no such table : Score
but it's running correctly on editor.

**Comment by robertohuertasm** [comment]
Sorry guys but I'm a little busy these days so I won't be able to help you as I would like. I promise to take a look at it asap and let you know.

**Comment by gilbertobitt** [comment]
no answer yet? so.. i probably should search for another solution for sqlite connection with unity!

**Comment by robertohuertasm** [comment]
Hey, it's completely up to you. I guess you know this is an open source project and I have no interest in you using it. If it does not get the job done then it's time to move on and collaborate with the project or seek for another tool. Is that simple.

**Comment by robertohuertasm** [comment]
@Borhenec @gilbertobitt I've just tried using the example and it works without any problem as you can see in this video:

[![example video](https://img.youtube.com/vi/DKxowkH0hIQ/0.jpg)](https://www.youtube.com/watch?v=DKxowkH0hIQ)

It must certainly be something specific of your code. Can you get any error message? Have you tried to debug it?

**Comment by gilbertobitt** [comment]
i will try here updating unity to a new version because i was watching the change log of the updates after mine version o unity (Unity 5.3.4p5 (64-bit)) about fixes on assets bundle on load assets streaming probably must be it! and i will do what u told me.. and like u said is open source.. i will try update/upgrade and let it more easy to manager!

**Comment by robertohuertasm** [comment]
If there's nothing new here I will proceed to close it. Feel free to continue the thread and I will reopen it again.

**Comment by mubeenfahmed** [comment]
Hi @robertohuertasm , I am experiencing a similar problem, but in my I am targeting **UWP**. I've followed your windows tutorial and did everything accordingly, but when I run the application on VS 2017, upon inserting values in db I get the following output.

`Exception thrown at 0x00007FF9B395A388 in Orbit-Ed.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002BAEAFDB50.
Exception thrown at 0x00007FF9B395A388 in Orbit-Ed.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002BAEAFDD20.
Exception thrown at 0x00007FF9B395A388 in Orbit-Ed.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002BAEAFE160.
Exception thrown at 0x00007FF9B395A388 in Orbit-Ed.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002BAEAFE2E0.
Exception thrown at 0x00007FF9B395A388 in Orbit-Ed.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000002BAEAFE2E0.
SQLiteException: ReadOnly
  at SQLite4Unity3d.PreparedSqlLiteInsertCommand.ExecuteNonQuery (System.Object[] source) [0x00000] in <filename unknown>:0 
  at SQLite4Unity3d.SQLiteConnection.Insert (System.Object obj, System.String extra, System.Type objType) [0x00000] in <filename unknown>:0 
  at SQLite4Unity3d.SQLiteConnection.Insert (System.Object obj) [0x00000] in <filename unknown>:0 
  at SQLite4Unity3d.SQLiteConnection+<>c__DisplayClass95_0.<InsertAll>b__0 () [0x00000] in <filename unknown>:0 
  at System.Action.Invoke () [0x00000] in <filename unknown>:0 
  at SQLite4Unity3d.SQLiteConnection.RunInTransaction (System.Action action) [0x00000] in <filename unknown>:0 
  at SQLite4Unity3d.SQLiteConnection.InsertAll (IEnumerable objects) [0x00000] in <filename unknown>:0 
  at loginService+<downloadImages>d__36.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 `

Kindly help, I am stuck.
