### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by mahgo** [codecoding/SQLite4Unity3d#43]
Is it possible to protect a database with a password?

**Comment by sandolkakos** [comment]
Here you are some people saying about this:
http://stackoverflow.com/questions/1381264/password-protect-a-sqlite-db-is-it-possible

**Comment by robertohuertasm** [comment]
@mahgo if you try what @sandolkakos is suggesting you let us know! 😀 
It seems that it will ultimately depend on the specific sqlite library that every platform is using.
