### ISSUE TITLE
iOS Support for arm7 and arm64

### ISSUE THREAD

**Issue by siddharth3322** [codecoding/SQLite4Unity3d#45]
Please not consider this thing as an issue, I have a question in mind so that asking here.

Whether this plugin support arm64 and arm7 both architecture or not?
At present I can able to build project successfully but it may be possible at submission time apple will reject this thing.

So I am confuse about this, use this plugin in actual project or not!!!
Please reply me for this so that I can continue my work.

**Comment by robertohuertasm** [comment]
I've recently submitted a Unity app to the App Store without any trouble so I guess you won't have any trouble too ;D

**Comment by siddharth3322** [comment]
@robertohuertasm really thanks for your reply, now I can move ahead with this plugin safely 👍 
You just reduce my stress.
