### ISSUE TITLE
How I update a specific item

### ISSUE THREAD

**Issue by dareyko** [codecoding/SQLite4Unity3d#46]
Hi
So I have a table name "situacion" and have this columns 

```
public int situacionID { get; set; }
    public string historia { get; set; }
    public string emocion { get; set; }
    public bool tarjeta { get; set; }``
```

I want to update "tarjeta" from false to true using "situacionID" as the reference,  something like this: UPDATE situacion SET tarjeta = true  WHERE situacionID = 6;

I make this in the DataServise archive, but I dont know how to put the condition to "situacionID"

```
public situacion update_tarjeta(){
        var p = new situacion{
            tarjeta = true,
        };
        _connection.Update (p);
        return p;
```

English it not my first language so I hope you understadn my crappy english.

**Comment by robertohuertasm** [comment]
dareyko I'd suggest you to use the documentation from this [Github repo](https://github.com/praeclarum/sqlite-net). You can use normal sql syntax. You're not forced to use linq.
