### ISSUE TITLE
how to use OrderByDescending

### ISSUE THREAD

**Issue by demon04551** [codecoding/SQLite4Unity3d#49]
Expression<Func<T, U>>,What is the meaning of this, how to use it

**Comment by sandolkakos** [comment]
This is an expression that can be used with Lambda. Something like that:

_connection.Table<Person>().OrderByDescending(x => x.Name).FirstOrDefault(); // Get only the first element

_connection.Table<Person>().OrderByDescending(x => x.Name); // Get all elements

**Comment by demon04551** [comment]
thank you,How do you know the sorted I want elements in what place

**Comment by sandolkakos** [comment]
You can store the result in a List or Array, like that:
List< Person > personList = _connection.Table< Person >().OrderByDescending(x => x.Name);

Later you can get the index of a specific element, like that:
Person person = personList.Where(x => x.Name = "Name").FirstOrDefault(); // you need to import the using System.Linq to use the Where clause.
int index = personList.IndexOf(person );

**Comment by demon04551** [comment]
How to update existing data,

**Comment by sandolkakos** [comment]
You need to select the data you want, change the properties and later apply the Update:
List< Person > personList = _connection.Table< Person >().OrderByDescending(x => x.Name);
Person person = personList.Where(x => x.Name = "Name").FirstOrDefault();
person.Name = "NewName";
_connection.Update(person);
