### ISSUE TITLE
Not able to use Select with where constraint 

### ISSUE THREAD

**Issue by pmohansivam** [codecoding/SQLite4Unity3d#50]

**Comment by sandolkakos** [comment]
Here is an example about how to select a person object by its name:
Person person = personList.Where(x => x.Name = "Name").FirstOrDefault(); // you need to import the using System.Linq to use the Where clause.

**Comment by robertohuertasm** [comment]
Closing this as it seems a duplicate of #51. This seems to be less elaborated than #51 that's why I'm closing it even though it was posted before.
