### ISSUE TITLE
Does it support WebGL?

### ISSUE THREAD

**Issue by NatsXDLageg** [codecoding/SQLite4Unity3d#53]
I was looking at the DataService.cs file and didn't find a condition to create the database file if in WebGL deployment.
The expected behaviour for WebGL is in the else directive? I tryied to run my Unity project and the console warned that the specified file could not be found.

**Comment by sandolkakos** [comment]
The WebGL platform doesn't support the Sqlite DLLs :(

**Comment by NatsXDLageg** [comment]
@sandolkakos @robertohuertasm 
Hmm, that is sad.
But if I put all my Sqlite code into my server, it would work, right?

**Comment by robertohuertasm** [comment]
If you put your SQLite in the server then you'll be dealing with an API and then you'll have to be connected.  Essentially, you'll be facing another kind of app architecture which won't involve the use of this library at all. Even you can think of different database alternatives which will provide you more performance.
