### ISSUE TITLE
Failed to load 'sqlite3.dll' on UWP (HoloLens)

### ISSUE THREAD

**Issue by sencyde** [codecoding/SQLite4Unity3d#65]
I'm trying to get my Unity App running on my HoloLens. In editor everything is working fine. I can even build my solution for UWP. 
But when i try to start the app on my HoloLens or Emulator it crashes and says: 
"Failed to load 'sqlite3.dll', expected x86 architecture, but was Unknown architecture. You must recompile your plugin for x86 architecture."
Any idea whats wrong?

**Comment by robertohuertasm** [comment]
Were you able to solve it? Did you need to do something special? I haven't had the opportunity to try hololens yet.
