### ISSUE TITLE
Unity 5 plugins colliding

### ISSUE THREAD

**Issue by markyama** [codecoding/SQLite4Unity3d#7]
When I try to Build your Example Unity project to Xcode for iOS, I get this error about colliding plugins:

Plugin 'sqlite3.dll' is used from several locations:
 Assets/Plugins/x86_64/sqlite3.dll would be copied to <PluginPath>/sqlite3.dll
 Assets/Plugins/x86/sqlite3.dll would be copied to <PluginPath>/sqlite3.dll
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.HostView:OnGUI()

I can remove one of the sqlite3.dll files from the plugin folder, but I want to make sure that it runs on 32bit or 64bit iOS devices. Any idea on what to do?

Love your project. I'm excited to be able to use sqlite for iOS, Windows Phone and Android. Thank you so much for creating SQLite4Unityd3d!!!

**Comment by codecoding** [comment]
Are you using Unity 5? For sure is something related to the inclusion of the x64 sqlite3.dll I'll look into it and try to find an elegant way to solve this. For the moment you can change the extension of the sqlite3.dll in your x64 folder when compiling for iOS. I guess it should work.

**Comment by markyama** [comment]
Forgot to mention, I'm using Unity 5.0.0f4. Thanks a lot.

**Comment by markyama** [comment]
Yes, I’m using Unity 5.0.0f4. OK, I’ll try changing the name of the sqlite3.dll in the x64 folder.

Thanks for the quick response.
Mark

**Comment by jawadmn** [comment]
Hmm... I'm not sure if this matters or not, but should the x64 or x32 plugin be used for iOS?

On a side note, the best fix would be to go to the plugin, uncheck "all platforms" (way at the top of the plugin settings), and check all but iOS.

Actually, I'm about to look into if there's settings to set which architecture (ie, x32 or x64) for iOS as well.

**Comment by codecoding** [comment]
Hi,

as  @jawadmn said it seems that in Unity 5 they have introduced the plugin inspector (http://docs.unity3d.com/Manual/PluginInspector.html). You can select the x86 plugin in your Unity Editor and select all but iOS in your inspector tab.

I've tested it in my iPad and it worked ok! 

I've tried by adding a specific iOS folder but anyway you have to unselect iOS from x86 & x64 so...

I think we can say this issue is closed if you don't have any inconvenience.

**Comment by markyama** [comment]
Thanks, turning off the x86 for iOS using the new plugin inspector in Unity 5 worked for me. The x64 library seems to work on both 32 bit and 64 bit iOS devices (iPhone 5 and iPhone 6). Thanks!

**Comment by kibiz0r** [comment]
Would it be sufficient to nest the 32-bit DLL under an Editor directory? I just ran into this today, and that was my workaround.

I'm trying not to rely on the new plugin inspector for managing this kind of stuff. We're trying to start using a package manager to bring in stuff like SQLite4Unity3d in an automated fashion, and having a manual step via the UI defeats the purpose.

**Comment by Gustavo-gcs** [comment]
I'm having the same trouble for Windows Phone 8.1, I think I'm configuring it wrong at the plugin inspector, I changed from unity 4 to unity 5, in unity 4 it works fine, but I can't figure out what I'm doing wrong even with the tutorial that comes with the project:

For this to work properly you will have to do some extra work.

You will have to follow these steps:


0. If you're targeting a the emulator an not a real device, then when it says WP/x86 you must read WP/ARM and the other way around. i.e. 1-5 is written considering you want to deploy to a real device.


1. In your Unity project's Plugin inspector, remove the WP/x86 folder items from the WP8Player.

2. Select the content of the WP/ARM folder and in the Plugin Inspector check "Don't process" and set them for WP8Player.

3. Make sure that the SQLite4Unity3d.dll in your plugin folder contains a placeholder to Assets/Plugins/SQLite4Unity3d.dll

4. Generate the project.

5. If you receive any error, go to Assets/Plugins/SQLite4Unity3d, check "Don't process" and set the architecture to the opposite you wan't to build for (i.e. if you aim for ARM then x86)

6. Add the following references:
	- sqlite.winmd (if you already have a sqlite reference in your project check it's the correct one in terms of architecture)
	- SQLite4Unity3d.dll (maybe your project already has this reference but don't forget to check the architecture)
	- SQLite for Windows Phone (Windows Phone/Extensions in your reference manager. You will have to download this with TOOLS > Extensions and Updates in your VS )

7. You're ready to go!

any help ?

**Comment by robertohuertasm** [comment]
@Gustavo-gcs have you watched this video? https://www.youtube.com/watch?feature=player_embedded&v=zVXr70fYxoA 

@kibiz0r I've not thought about the scenario that you propose. Is it working for you? It's that's the case maybe we could think of changing the current Inspector dependency, provided it is possible.

**Comment by Gustavo-gcs** [comment]
it worked for the example, it seems that I was using an old version of the plugins, that version has the tutorial for unity 5, but some of the folder names and other things really don't match with the plugin used in the video, then I've downloaded the plugins again...

the only thing that I made different from the video was the build settings, I've builded for Phone 8.1, then in VS, I referenced the sqlite for Windows Phone 8.1 and the sqlite.winmd (I don't know if it's necessary the sqlite.winmd), I've got some alerts, but it worked fine in the example, thanks for the assistance, I'll put the list of the plugins in my app and test again, it'll work now I hope,

thanks again

**Comment by robertohuertasm** [comment]
Hi Gustavo,

 

I’m glad that you could make it.

 

Let me know if you find further issues.

 

Best regards,

 

Roberto.
