### ISSUE TITLE
Simple CRUD!!!

### ISSUE THREAD

**Issue by ErEllison** [codecoding/SQLite4Unity3d#84]
Hi there 
i personally appreciate your job , well done !
but i'm little bit confused about it !!!
can you please show me a piece of code that handles a simple CRUD???

**Comment by robertohuertasm** [comment]
You have some insert and read examples in the `Example` folder (https://github.com/codecoding/SQLite4Unity3d/blob/master/Example/Assets/Scripts/DataService.cs#L71).

You should probably take a look at [sqlite-net](https://github.com/praeclarum/sqlite-net) too.

Of course, if you want to know more you can also take a look at the [code](https://github.com/codecoding/SQLite4Unity3d/blob/master/Example/Assets/Scripts/SQLite.cs).

**Comment by naisu1412** [comment]
any idea how to do an update?

here's my simple code:
` string query = "UPDATE Planet" +
            "SET Name = 'NewPlanet'" +
            "";
        _connection.Update(query);`

here's the Planet Class

`public class Planet
{
    [SQLite4Unity3d.PrimaryKey, SQLite4Unity3d.AutoIncrement]
    public int PlanetID {get;set;}
    public float Mass {get;set;}
    public string planetDesc {get;set;}
    public string Name {get;set;}
    public string texture {get;set;}
    public int moons {get;set;}
    public float diameter {get;set;}        //size in km, will be converted later in e units
    public float distanceFromTheSun {get;set;}
    public int solarSystemID {get;set;}      //foreign key


    public override string ToString ()
	{
		return string.Format ("Planet:  {0} and mass : {1} ", Name, Mass);
	}
}`
