### ISSUE TITLE
Unity5 breaks Windows Phone compatibility

### ISSUE THREAD

**Issue by codecoding** [codecoding/SQLite4Unity3d#9]
Apparently Community.CsharpSqlite.WP7 dll is not supported by Unity 5. I don't really see why this is happening as I keep getting an error like this:

Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

Certainly, something must have changed in Unity 5 regarding Windows Phone so I'll have to investigate for a while and see if I can solve it.

Meanwhile, if you want to deploy to WP use the 4.x versions.

**Comment by codecoding** [comment]
Good news, I've got it working!! I'm planning to upload the new code tomorrow and I'll update the documentation, too, as now the plugin system get a little bit trickier than before!

Best regards,
Roberto.

**Comment by babazookz** [comment]
Good news, can't wait for the update!

**Comment by babazookz** [comment]
Any news on update?

**Comment by codecoding** [comment]
Sorry, but something came in and it was impossible to make the changes. Maybe tonight!

**Comment by Software-Dev** [comment]
getting a license error: this plugin is only supported in Unity Pro. 
Is this just the IOS version causing the error or do you need a pro version for using this?

**Comment by codecoding** [comment]
Hi @Software-Dev, it's definitely a plugin supported by Unity Personal edition. I use it myself in my own app. Never mind those warnings. They appear from time to time but there's no problem with it. Is it making impossible to run your app?

**Comment by Software-Dev** [comment]
Nope everything is working great this is a great plugin. Thanks!

**Comment by codecoding** [comment]
Regarding the error about the Unity Pro, if you want to get rid of it just do this:
1. put the x86 & x64 folders outside the plugin folder .
2. create an iOS folder inside the plugin folder and put your x86 & x64 folders there.

**Comment by babazookz** [comment]
And what about Windows Phone and Reflection error?

**Comment by codecoding** [comment]
I've been trying to prepare the upload today but somehow it got all messed and now it doesn't work for WP8 nor Android... :( I guess is going to take more than I thought. Meanwhile, you can use the 4.x version.

**Comment by babazookz** [comment]
It is hard for me to use 4.x version because my game is using the new UI in version 5.x, and when it's converted to 4.x it doesn't work.
So i am waiting your plugin for version 5.x like i am waiting the sun after rain :)

**Comment by codecoding** [comment]
Sorry to hear that!! I'll give it a shot today but I can't promise anything. If not today then it will have to wait until next Wednesday!! :(

**Comment by codecoding** [comment]
I forgot to tell you. The other day I uploaded a beta version into a new branch called Unity-5. If you feel adventurous then it's all up to you but I cannot guarantee that it works ok.

**Comment by codecoding** [comment]
@babazookz What platforms are you targeting? You can use the current version in Unity 5. The only platform not working at the moment with Unity 5 is WP.

I've got the new version almost ready. Android & WP working ok with latest version of SQLite-net but unfortunately iOS seems to complaint about JIT compiler errors... The current version works better for iOS as it allows you to use LINQ.

**Comment by codecoding** [comment]
Finally solved and updated!! Master branch now supports Unity 5 and 4.x and uses the latest version of SQLite. It works flawlessly in iOS, Android and WP and allows Linq in iOS.

Best regards.

**Comment by babazookz** [comment]
Hi @codecoding, i am really happy to hear you have managed to solve the issue. I can't wait to try it!

I'll get back to you with feedback, you did great job so far !!!

P.S. i am making the game for all three platforms, so far Android works, WP8 works without database and iOS haven't tried since i don't have iOS dev account yet.

**Comment by babazookz** [comment]
Hi i tried but it is not working. I was doing by your notes you provided in the project. I'll show you some pictures of how my Plugins folder looks like and what error do i get when i try to run my game through Emulator in VS2012.

My Plugins folder looks like this:
http://i.imgur.com/nmVz4Fm.png

This is the error when i run my game on emulator after building the project:
Exception: DllImport cannot be used on user-defined methods.
Type: System.NotSupportedException
Module: SQLite4Unity3d
InnerException: <No Data>
AdditionalInfo:<No Data>
   at SQLite4Unity3d.SQLite3.Open(Byte[] filename, IntPtr& db, Int32 flags, IntPtr zvfs)
   at SQLite4Unity3d.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
   at DataService..ctor(String DatabaseName)
   at DataAccessLayer.OpenDatabase(String dbName)
   at MainMenuCtrl.Awake()
   at MainMenuCtrl.$Invoke2(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method)

What am i doing wrong?

How to do this: 
4. Add the following references:
	- sqlite.winmd (directly in the ARM folder) ???

**Comment by babazookz** [comment]
I need my project(game built in Unity3D) to work on WP8 only. So what do i need from plugins?

**Comment by codecoding** [comment]
Let's see. Provided that you're using Unity 5 and want to run your game in the emulator you should follow the instructions and where it says ARM you should have to read x86.

The error suggests that you don't have Sqlite for Windows phone installed in your Visual Studio extensions. 

When you open your generated Wp solution you have to be sure that the generated references are ok. You have to have a reference to SQLite4Unity3d (x86 in this case), one to sqlite (through sqlite.winmd) and another one to Sqlite for Windows Phone (installed extension)

**Comment by babazookz** [comment]
Ok, it seems i don't understand you. So i will tell you steps i did and maybe you can tell me where i did go wrong:

(your instructions attached in the plugin)
For this to work properly you will have to do some extra work.

You will have to follow these steps:
1. In your Unity project, remove the WP/x86 folder. - I DID THIS
2. Select the content of the WP/ARM folder and in the Plugin Inspector check "Don't process". - EVERY CONTENT OF THAT FOLDER I CHECKED "DON'T PROCESS"
3. Make sure that the SQLite4Unity3d contains a placeholder to Assets/Plugins/SQLite4Unity3d.dll - IN SQLite4Unity3d  I CREATED PLACE HOLDER TO Assets/Plugins/SQLite4Unity3d.dll
3. Generate the project. - WHEN I CLICK BUILD (TO GENERATE PROJECT) I GET THE FOLLOWING ERROR: Exception: SQLite4Unity3d plugin must not have both AnyCPU and architecture specific instances.
SO I TRIED TO REMOVE ONE SQLite4Unity3d FILE AND JUST LEAVE THE OTHER ONE WITH SELECTED PLATFORM WINPLAYER8 AND TRIED TO BUILD THE PROJECT. I SUCCEEDED. THEN I OPENED THE PROJECT IN VISUAL STUDIO 2012 AND DID THE FOLLOWING:
CHECKED IS THERE SQLite4Unity3d.dll (CORRECT, IT WAS)
ADDED SQLITE FOR WINDOWS PHONE REFERENCE (DOWNLOADED THROUGH EXTENSIONS AND UPDATES)
- sqlite.winmd (directly in the ARM folder) - THIS I AM UNABLE TO DO, BECAUSE I DON'T UNDERSTAND. EVERYTIME I TRY TO ADD SQLITE.WINMD AS REFERENCE VS2012 SAYS IT ALREADY EXISTS.

Which part do you see as something i did wrong?

**Comment by codecoding** [comment]
Sorry for my instructions. I wrote them in a rush. Now it's clear to me that I have to reformulate them. 

1. In your case you should remove the ARM folder as you want to use your app in the emulator. Remember that when you deploy to devices you need a different architecture dll,  namely ARM. In fact, there's no need that you remove any folder as long as you use the unity plug-in inspector and unchek x86 or ARM dlls for wp8 (depending whether you're deploying to emulator or device)

About sqlite.winmd, if it says so is that the reference is ok. If you've got a sqlite reference it's ok.

It seems to me that the problem is that you're using the ARM dlls instead of the x86.

Let me know if that helps.

**Comment by codecoding** [comment]
Hi, I'm really glad you could make it. When deploying to real device you should use the ARM version of the plugin so you'll have to change the references accordingly and change build settings.

You could change your project properties so depending on the building settings it will change the reference automatically for you. You'll have to edit your project file for that. As the vs project is auto generated In couldn't provide that solution out of the box.

**Comment by babazookz** [comment]
Roberto thank you very much for everything, but the only thing you need is just little better instructions :) you can use me as an example and everything i tried :) ! 

But plugin works and i can confirm that! In couple of days i'll try on real device too and get back to you.

**Comment by codecoding** [comment]
You're very welcome! You're right but I tried to upload the new version before I left on holidays so you could use it and that's why the instructions are so succinct. 

Now I'm writing from my mobile phone but when I have a chance I will write better instructions and maybe start a little wiki. 

Kind regards.
